FROM alpine

ENV S6_OVERLAY_VERSION=v2.1.0.2

RUN apk update \
    && apk add gnupg curl \
    && curl -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_OVERLAY_VERSION}/s6-overlay-amd64.tar.gz | tar xfz - -C /

COPY root /

ENTRYPOINT ["/init"]
CMD []
